# Generated by Django 5.0.4 on 2024-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque essa opção para desativar o usuário e impedir o login.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Marque essa opção para conceder acesso a área administrativa.', verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Marque essa opção para conceder todos os privilégios.', verbose_name='Superusuário'),
        ),
    ]
