# Generated by Django 5.0.4 on 2024-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Marque essa opção para conceder todos os privilégios, sem a necessidade de permissões.', verbose_name='Superusuário'),
        ),
    ]
