# Generated by Django 5.0.4 on 2024-05-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_sheet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Atendimento')),
                ('attendance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_history', to='attendance_sheet.attendancesheet')),
                ('doctor_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Atendimento',
                'verbose_name_plural': 'Históricos de Atendimento',
                'db_table': 'medical_care_histories',
                'ordering': ['service_date'],
            },
        ),
    ]
