# Generated by Django 5.0.4 on 2024-05-01 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sheet', '0002_alter_attendancesheet_filled_by'),
        ('medical_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcarehistory',
            name='attendance_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_history', to='attendance_sheet.attendancesheet', verbose_name='Ficha de Atendimento'),
        ),
        migrations.AlterField(
            model_name='medicalcarehistory',
            name='doctor_attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attended', to=settings.AUTH_USER_MODEL, verbose_name='Médico(a) que Atendeu'),
        ),
    ]
