# Generated by Django 5.0.4 on 2024-05-01 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sheet', '0004_alter_attendancesheet_options'),
        ('medical_history', '0002_alter_medicalcarehistory_attendance_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcarehistory',
            name='attendance_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_history', to='attendance_sheet.attendancesheet', verbose_name='Ficha de Atendimento'),
        ),
    ]
