# Generated by Django 5.0.4 on 2024-05-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(verbose_name='Número da Ficha')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Nome do Paciente')),
                ('clinical_history', models.TextField(blank=True, max_length=500, null=True, verbose_name='História Clínica')),
                ('classification', models.CharField(choices=[('Red', 'Vermelho'), ('Orange', 'Laranja'), ('Yellow', 'Amarelo'), ('Green', 'Verde'), ('Blue', 'Azul'), ('Ignored', 'Ignorado')], max_length=10, verbose_name='Classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('filled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Atendimento',
                'verbose_name_plural': 'Fichas de Atendimento',
                'db_table': 'attendance_sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
