# Generated by Django 5.0.4 on 2024-05-01 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sheet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='filled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_by', to=settings.AUTH_USER_MODEL, verbose_name='Preenchido por'),
        ),
    ]
