# Generated by Django 5.0.4 on 2024-05-01 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sheet', '0002_alter_attendancesheet_filled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='card_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'O número da ficha deve ser maior que 0.')], verbose_name='Número da Ficha'),
        ),
    ]
