# Generated by Django 5.0.4 on 2024-05-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sheet', '0003_alter_attendancesheet_card_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesheet',
            options={'ordering': ['created_at'], 'verbose_name': 'Ficha de Atendimento', 'verbose_name_plural': 'Fichas de Atendimento'},
        ),
    ]
